name: Test package against latest Vertica

# Triggers the workflow on push or pull request events
on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    services:
      vertica:
        image: ghcr.io/ratiopbc/vertica-ce:latest
        ports:
          - 5433:5433
          - 5444:5444
        env:
          VERTICA_DB_NAME: docker
          VMART_ETL_SCRIPT: ''
          VMART_ETL_SQL: ''
    steps:
    - uses: actions/checkout@v3
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync --python ${{ matrix.python-version }}
    - name: Build package
      run: uv build
    - name: Check
      run: uvx twine check dist/*.tar.gz
    - name: Test Basic
      run: uv run pytest tests/functional/adapter/test_basic.py
    - name: Test Constraints
      run: uv run pytest tests/functional/adapter/constraints/test_constraints.py
    - name: Test Incremental
      run: uv run pytest tests/functional/adapter/incremental/
    - name: Test Concurrency
      run: uv run pytest tests/functional/adapter/concurrency/
    - name: Test Doc Generate
      run: uv run pytest tests/functional/adapter/test_doc_gen.py
    - name: Test Data Type Boolean
      run: uv run pytest tests/functional/adapter/test_data_types.py
    - name: Test Concat
      run: uv run pytest tests/functional/adapter/utils/test_concat.py
    - name: Test Data Type Int
      run: uv run pytest tests/functional/adapter/utils/data_type/
    - name: Test Last Relation Modified
      run: uv run pytest tests/functional/adapter/test_get_last_relation_modified.py
    - name: Test  Relation Caching
      run: uv run pytest tests/functional/adapter/test_list_relations_without_caching.py
    - name: Test Store test Failure
      run: uv run pytest tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
    - name: Test Date Spine
      run: uv run pytest tests/functional/adapter/utils/test_date_spine.py
    - name: Test DBT Show
      run: uv run pytest tests/functional/adapter/dbt-show/test_dbt_show.py
    - name: Test DBT Clone
      run: uv run pytest tests/functional/adapter/dbt_clone/
    - name: Test Seeds
      run: uv run pytest tests/functional/adapter/seeds/test_seeds.py



      




    


